/* Generated By:JavaCC: Do not edit this line. QueryParserConstants.java */
package edu.washington.cse.codestats;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface QueryParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EXISTS = 5;
  /** RegularExpression Id. */
  int COUNT = 6;
  /** RegularExpression Id. */
  int STMT = 7;
  /** RegularExpression Id. */
  int EXPR = 8;
  /** RegularExpression Id. */
  int WITHIN = 9;
  /** RegularExpression Id. */
  int WHERE = 10;
  /** RegularExpression Id. */
  int AND = 11;
  /** RegularExpression Id. */
  int OR = 12;
  /** RegularExpression Id. */
  int IS = 13;
  /** RegularExpression Id. */
  int IN = 14;
  /** RegularExpression Id. */
  int NOT = 15;
  /** RegularExpression Id. */
  int ANY = 16;
  /** RegularExpression Id. */
  int ALL = 17;
  /** RegularExpression Id. */
  int THIS = 18;
  /** RegularExpression Id. */
  int IDENT = 19;
  /** RegularExpression Id. */
  int WHATEVER = 20;
  /** RegularExpression Id. */
  int OPERATOR = 21;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"exists\"",
    "\"count\"",
    "\"statement\"",
    "\"expression\"",
    "\"within\"",
    "\"where\"",
    "\"and\"",
    "\"or\"",
    "\"is\"",
    "\"in\"",
    "\"not\"",
    "\"[?]\"",
    "\"[*]\"",
    "\"[0]\"",
    "<IDENT>",
    "<WHATEVER>",
    "<OPERATOR>",
    "\":\"",
    "\"{\"",
    "\"}\"",
    "\".\"",
  };

}
